### ISSUE TITLE
Readme should be updated to reflect some required elements in web.config

### ISSUE THREAD

**Issue by paulsterling** [umbraco/vsts-uaas-deploy-task#5]
The UmbracoDeploy specific sections need to be added as does the DeployApiKey in order for the local site to run - and if any deployment would be done for content/media; same for restore

**Comment by paulsterling** [comment]
Also the Deploy Dashboard config needs to be added - if content will be deployed local > cloud

**Comment by paulsterling** [comment]
It is not obvious, or it wasn't to me anyhow, that the Variables need to be added to the build definition:

BuildConfiguration = release
BuildPlatform = any cpu

Update docs to reflect this step

**Comment by paulsterling** [comment]
Not really specific to umbraco cloud, but perhaps noting that as the .sln is being used for the build, all files that should be deployed with the build to the cloud site should be included in the project - i.e., css, scripts, etc...

**Comment by paulsterling** [comment]
And should remove reference to UaaS > Umbraco Cloud where applicable

NB:  just adding all these here so I cam reference with a PR

**Comment by sitereactor** [comment]
Closing this issue as the readme file has been updated.
