### ISSUE TITLE
No task definition found matching id

### ISSUE THREAD

**Issue by john-mckillip** [umbraco/vsts-uaas-deploy-task#8]
Hi. I am running into an issue with the task and not sure the cause. I have installed the task following the directions under How to use this Task. When testing the pipeline in VSO, I am getting this error:

```
Download all required tasks.
Downloading task: DeployUmbracoCloudRepository
##[warning]Failed to download task 'DeployUmbracoCloudRepository'. Error No task definition found matching id c1573af0-37b0-11e6-8e3f-ddb065832fbd and version 0.2.5. You must register the task definition before uploading the package.
##[warning]Back off 26.449 seconds before retry.
##[warning]Failed to download task 'DeployUmbracoCloudRepository'. Error No task definition found matching id c1573af0-37b0-11e6-8e3f-ddb065832fbd and version 0.2.5. You must register the task definition before uploading the package.
##[warning]Back off 26.558 seconds before retry.
##[error]No task definition found matching id c1573af0-37b0-11e6-8e3f-ddb065832fbd and version 0.2.5. You must register the task definition before uploading the package.
```
Wondering if there is something I missed when uploading the task to my account? Please let me know!

**Comment by sitereactor** [comment]
TBH i don't know if the installation instructions are still valid, as this was created/writing a long time ago, from back when Azure DevOps was called VSTS 🙂 ... That being said, if you followed the step by step guide I would assume that it works. I haven't tried it myself for a very long time though.

**Comment by john-mckillip** [comment]
@sitereactor  Thanks for responding. Looks like it may be something with the different version listed in task.json vs task.loc.json. I was able to get past the error by getting rid of the task.loc.json file. Cheers!
